### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by shayaulman** [Yiddishe-Kop/fullstack-graphql#1]
Congratulations and thanks for this nice demo project!
I have a problem with starting the server. I get the following error:
```
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module '@babel/core'
Require stack:
- /Users/yehudaneufeld/Downloads/fullstack-graphql-master/node_modules/babel-watch/babel-watch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/yehudaneufeld/Downloads/fullstack-graphql-master/node_modules/babel-watch/babel-watch.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yehudaneufeld/Downloads/fullstack-graphql-master/node_modules/babel-watch/babel-watch.js'
  ]
}
```
Any idea?

**Comment by Yiddishe-Kop** [comment]
As the error states, the `@babel/core` dependency is missing.
Just run `npm i @babel/core -g`.
The reason it's not listed in my `package.json` is because it's a peer dependancy which doesn't get installed automatically. Don't ask me why... I also had to install it manually.
But I should really add it to the dependancy list. 
Thanks @shayaulman! 😊

**Comment by shayaulman** [comment]
Yes. This solved the "issue".
And that's why I'm going to close now the real issue...
